twist_mux:
  ros__parameters:
    topics:
      user:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 20
